#define WINDOW_TITLE "Best Game"
#define FPS 20

#define WINDOW_WIDTH 900
#define WINDOW_HEIGHT 900

#define SPRITE_SIZE 50

#define RAIN_SPEED 20
#define TRAVOYADNYE_SPEED 10.0

#define WOLF_COUNT 10
#define COW_COUNT 10
#define PIG_COUNT 10
#define GRASS_COUNT 30

#define DANGER_RADIUS 200

#define CALL_DAWN_SEX 0

#define ALIVE_HP 100
#define ALIVE_HUNGER 20